In [1]:
# Reads in the data
berths=open("/home/mathsys1/Documents/Trains/TrainData/Steve/TD_201706121200.txt")
data=readlines(berths)

311067-element Array{String,1}:
 "1497265223312\$<CA_MSG>ESCA138513871G29115958</CA_MSG>\r\n"
 "1497265223328\$<SF_MSG>CCSFBB00115958</SF_MSG>\r\n"        
 "1497265223374\$<SF_MSG>G2SF91F7115959</SF_MSG>\r\n"        
 "1497265223374\$<SF_MSG>SSSF3108115959</SF_MSG>\r\n"        
 "1497265223390\$<SF_MSG>LCSF157F115959</SF_MSG>\r\n"        
 "1497265223390\$<SF_MSG>CASF8A04115959</SF_MSG>\r\n"        
 "1497265223406\$<CA_MSG>BNCA042300359S60115959</CA_MSG>\r\n"
 "1497265223406\$<CA_MSG>BECAE114E1121W12115959</CA_MSG>\r\n"
 "1497265223421\$<SF_MSG>T2SF5979115959</SF_MSG>\r\n"        
 "1497265223437\$<CA_MSG>Q1CA041604081Y37115959</CA_MSG>\r\n"
 "1497265223437\$<SF_MSG>LBSF02B8115959</SF_MSG>\r\n"        
 "1497265223453\$<SF_MSG>WISF6784115959</SF_MSG>\r\n"        
 "1497265223453\$<SF_MSG>G1SF6640115959</SF_MSG>\r\n"        
 ⋮                                                           
 "1497268800051\$<CA_MSG>MDCA42194221****125959</CA_MSG>\r\n"
 "1497268800051\$<SF_MSG>X1SF2AE712595

In [ ]:
for i=1:length(data)
    if contains(data[i],"STIN")
        print(data[i])
    end
end

In [4]:
dataclean=Array(String,length(data))
j=1
q=0
number="0123456789"
for i=1:length(data)     
    if contains(data[i],"<CA_MSG>")# Removes all unnecessary signal movements
        #for k=1:8
        #    if contains(number,string(data[i][26+k]))
        #        q=q+1
        #    end
        #end
        if contains(data[i],"****")==false#&&q==8 # Removes the train headcodes that have reported in with an error
            dataclean[j]=data[i]
            j=j+1
        end
    end
    q=0
end
dataclean=dataclean[1:j-1]

99263-element Array{String,1}:
 "1497265223312\$<CA_MSG>ESCA138513871G29115958</CA_MSG>\r\n"
 "1497265223406\$<CA_MSG>BNCA042300359S60115959</CA_MSG>\r\n"
 "1497265223406\$<CA_MSG>BECAE114E1121W12115959</CA_MSG>\r\n"
 "1497265223437\$<CA_MSG>Q1CA041604081Y37115959</CA_MSG>\r\n"
 "1497265223468\$<CA_MSG>ASCAI057NS572N38115959</CA_MSG>\r\n"
 "1497265223484\$<CA_MSG>BNCAASAP00572N38115959</CA_MSG>\r\n"
 "1497265223499\$<CA_MSG>EHCAEHFAEHFX1W12115959</CA_MSG>\r\n"
 "1497265223499\$<CA_MSG>KXCA058205602T47115959</CA_MSG>\r\n"
 "1497265223546\$<CA_MSG>D4CA024602341L46115959</CA_MSG>\r\n"
 "1497265223562\$<CA_MSG>C2CA297629722J12115959</CA_MSG>\r\n"
 "1497265223578\$<CA_MSG>ZECA138513871G29115959</CA_MSG>\r\n"
 "1497265223593\$<CA_MSG>YKCA033303371S11115959</CA_MSG>\r\n"
 "1497265223593\$<CA_MSG>G1CAN137N1331S31115959</CA_MSG>\r\n"
 ⋮                                                           
 "1497268799817\$<CA_MSG>NXCA0206R2059M26125959</CA_MSG>\r\n"
 "1497268799848\$<CA_MSG>R3CA361836161L

In [ ]:
number="0123456789"
q=0
for i=1:8
    if contains(number,string(data[7][26+i]))
        q=q+1
    end
end
q

In [5]:
# Creates an array containing all the unique train headcodes found in the data
trains=Array(String,length(dataclean)+1)
for i=1:length(dataclean)+1
    trains[i]="sausage"
end

j=1                                    
s=1                                     
                                        
for i=1:length(dataclean)
    a=dataclean[i][35:38]
    for k=1:j
        if contains(trains[k],a)==true
            s=s+1
            break
        end
    end
    if s==1
        trains[j]=a
        j=j+1
    end
    s=1
end
println(j)
trains=trains[trains.!="sausage"]

2259


2258-element Array{String,1}:
 "1G29"
 "9S60"
 "1W12"
 "1Y37"
 "2N38"
 "2T47"
 "1L46"
 "2J12"
 "1S11"
 "1S31"
 "2G55"
 "1L52"
 "2M52"
 ⋮     
 "5A88"
 "2T33"
 "1R92"
 "A245"
 "1B59"
 "2S64"
 "2W88"
 "2U42"
 "2Y35"
 "9M29"
 "7379"
 "5P39"

In [6]:
# Gives each train found in the previous cell an array containing all the
# berth movements for that train
Trains=Array(Array,length(trains))
for i=1:length(trains)
    Trains[i]=Array(String,length(dataclean)+1)
    for j=1:length(dataclean)+1
        Trains[i][j]="sausage"
    end
end
s=1
for i=1:length(trains)
    for j=1:length(dataclean)
        if contains(dataclean[j][35:38],trains[i])
            Trains[i][s]=dataclean[j]
            s=s+1
        end
    end
    Trains[i]=Trains[i][Trains[i].!="sausage"]
end

In [ ]:
Trains

In [ ]:
writedlm("/home/mathsys1/Documents/Trains/Trains.csv",Trains)

In [ ]:
# A code that subject to a set of imposed checks identifies a list of
# nodes which I have called border nodes and creates a unique list
# of these objects of interest
Bordernodes=Array(String,length(dataclean),2)
for i=1:length(dataclean)
    Bordernodes[i,1]="sausage"
    Bordernodes[i,2]="sausage"
end
p=1
q=1
for i=1:length(Trains)
    for j=1:length(Trains[i])-1
        if Trains[i][j][23:24]!=Trains[i][j+1][23:24]&&Trains[i][j][27:30]==Trains[i][j+1][27:30]&&Trains[i][j][31:34]==Trains[i][j+1][31:34]            
            a=Trains[i][j][23:24]*Trains[i][j][31:34]*Trains[i][j+1][23:24]*Trains[i][j+1][27:30]
            b=Trains[i][j+1][23:24]*Trains[i][j+1][27:30]*Trains[i][j][23:24]*Trains[i][j][31:34]
            c=Trains[i][j][23:24]*Trains[i][j][27:30]*Trains[i][j+1][23:24]*Trains[i][j+1][31:34]
            for k=1:p
                if contains(Bordernodes[k,1],a)==true||contains(Bordernodes[k,1],b)==true
                    q=2
                    break
                end
            end
            if q==1
                Bordernodes[p,1]=c[1:6]
                Bordernodes[p,2]=a[7:12]
                p=p+1
            end
            q=1
        end
    end


end

Bordernodes=Bordernodes[1:p-1,:]

In [ ]:
# A code which augments the data and introduces the concept of two area
# codes which can now model inter-area movements and at the same time
# replaces the duality of the bordernodes with the other of the pair
# in the actual dataset
s=1
t=1
k=1
w=1
z=1
for i=1:length(dataclean)
    for j=1:Int64(length(Bordernodes)/2)
        if contains(dataclean[i][23:24],Bordernodes[j,2][1:2])&&contains(dataclean[i][27:30],Bordernodes[j,2][3:6])&&t==1
            dataclean[i]=dataclean[i][1:22]*Bordernodes[j,1][1:2]*dataclean[i][23:24]dataclean[i][27:55]
            s=2
            z=z+1
        end
        if contains(dataclean[i][23:24],Bordernodes[j,1][1:2])&&contains(dataclean[i][27:30],Bordernodes[j,1][3:6])&&s==1
            dataclean[i]="sausage"
            t=2
            break
        end
        #if contains(dataclean[i][23:24],Bordernodes[j,2][1:2])&&contains(dataclean[i][31:34],Bordernodes[j,2][3:6])#&&s==1
        #    dataclean[i]=dataclean[i][1:24]*dataclean[i][23:24]*dataclean[i][27:55]
        #    dataclean[i]=dataclean[i][1:22]*Bordernodes[j,1][1:2]*dataclean[i][25:55]
        #    t=2
        #    w=w+1
        #end
    end
    
    if s==1 && t==1
        dataclean[i]=dataclean[i][1:24]*dataclean[i][23:24]*dataclean[i][27:55]
        k=k+1
    end
    s=1
    t=1
end
dataclean=dataclean[dataclean.!="sausage"]

In [ ]:
k

In [ ]:
# A code that can check whether the above code is having an affect
s=1
for i=1:length(dataclean)
    if dataclean[i][23:24]!=dataclean[i][25:26]
        s=s+1
        #println(i)
    end
end
s

In [ ]:
# Find the same set of data for each train but now utilises the new
# data format so has the second area code
Trains=Array(Array,length(trains))
for i=1:length(trains)
    Trains[i]=Array(String,length(dataclean)+1)
    for j=1:length(dataclean)+1
        Trains[i][j]="sausage"
    end
end
s=1
for i=1:length(trains)
    for j=1:length(dataclean)
        if contains(dataclean[j][35:38],trains[i])
            Trains[i][s]=dataclean[j]
            s=s+1
        end
    end
    Trains[i]=Trains[i][Trains[i].!="sausage"]
end

In [ ]:
# Loops through all of the arrays created earlier for individual trains
# and from that creates a list of unique inter-area connections
#Interconnections=Array(String,length(dataclean)+1)
#Interweights=ones(length(dataclean)+1)
#for i=1:length(dataclean)+1
#    Interconnections[i]="sausage"
#end
#p=1
#q=1
for i=1:length(Trains)
    for j=1:length(Trains[i])-1
        if Trains[i][j][23:24]!=Trains[i][j+1][23:24]&&Trains[i][j][23:24]==Trains[i][j][25:26]
            Trains[i][j]=Trains[i][j][1:24]*Trains[i][j+1][23:24]*Trains[i][j][27:55]
            #a=Trains[i][j][23:24]*Trains[i][j][31:34]*Trains[i][j+1][23:24]*Trains[i][j+1][27:30]
            #b=Trains[i][j+1][23:24]*Trains[i][j+1][27:30]*Trains[i][j][23:24]*Trains[i][j][31:34]
            #for k=1:p
            #    if contains(Interconnections[k],a)==true||contains(Interconnections[k],b)==true
            #        q=2
            #        Interweights[k]=Interweights[k]+1
            #        break
            #    end
            #end
            #if q==1
            #    Interconnections[p]=a
            #    p=p+1
            #end
            #q=1
        end
    end
end

In [ ]:
# Removes the dummy variables in the previously created array
#Interconnections=Interconnections[Interconnections.!="sausage"]

In [ ]:
#Creates an array of dummy variables required for the next cell
weights=Array(String,length(dataclean)+1)
for n=1:length(dataclean)+1
    weights[n]="sausage"
end

In [ ]:
# Creates a list of unique intra-area connections 
z=1
s=1
for i=1:length(dataclean)
    a=dataclean[i][23:24]
    b=dataclean[i][25:26]
    c=dataclean[i][27:30]
    d=dataclean[i][31:34]
    e=a*b*c*d
    for k=1:z
        if contains(weights[k],e)==true
            s=2
            break
        end
    end
    if s==1
        weights[z]=e
        z=z+1
    end
    s=1
end
z
weights

In [ ]:
# Separates the list of unique intra-area connections
# and gives an array that can be read into a external file easier
connections=Array(String,z-1,2)
for i=1:z-1
    a=weights[i][1:2]
    b=weights[i][3:4]
    c=weights[i][5:8]
    d=weights[i][9:12]
    connections[i,1]=a*c
    connections[i,2]=b*d
end
connections

In [ ]:
s=0
for i=1:Int64(length(connections)/2)
    if connections[i,1][1:2]!=connections[i,2][1:2]
        s=s+1
        #println(connections[i,1]," ",connections[i,2])
    end
end
s
writedlm("/home/mathsys1/Documents/Trains/Intra Connections.csv",connections)

In [ ]:
connections[1,2][1:2]

In [ ]:
# A short script that can return all of the unique connections from the
# previous array but only contains connections for one specified area code
areaconnect=Array(String,Int64(length(connections)/2),2)
h=1
for j=1:Int64(length(areaconnect)/2)
    if contains(connections[j,1][1:2],"UR")==true
        areaconnect[h,1]=connections[j,1]
        areaconnect[h,2]=connections[j,2]
        h=h+1
    end
end
areaconnect=areaconnect[1:h-1,:]

In [ ]:
# Writes the previous array to a file in the user area
writedlm("/home/mathsys1/Documents/Trains/area.csv",areaconnect)

In [ ]:
function uniquenodes(dataclean,nodes)   #requires two arrays the first which
j=1                                     #is the data and the second which
s=1                                     #is an array of dummy values of 
t=1                                     #size one greater than the first
for i=1:length(dataclean)
    a=dataclean[i][23:24]
    b=dataclean[i][27:30]
    c=a*b
    for k=1:j
        if contains(nodes[k],c)==true
            s=2
            break
        end
    end
    if s==1
        nodes[j]=c
        j=j+1
    end
    s=1
end
for i=1:length(dataclean)
    a=dataclean[i][25:26]
    b=dataclean[i][31:34]
    c=a*b
    for k=1:j
        if contains(nodes[k],c)==true
            t=2
            break
        end
    end
    if t==1
        nodes[j]=c
        j=j+1
    end
    t=1
end
    println(j)
    nodes=nodes[1:j-1]
end

In [ ]:
# Creates an array of dummy variables required 
# to run the above function
nodes=Array(String,length(dataclean)+1)
for n=1:length(dataclean)+1
    nodes[n]="sausage"
end
uniquenodes(dataclean,nodes)j

In [ ]:
# Removes all of the border nodes from the array of unique nodes
for l=1:Int64(length(Bordernodes)/2)
    for m=1:length(nodes)
        if contains(nodes[m],Bordernodes[l,2])
            nodes[m]="sausage"
        end
    end
end
#nodes=nodes[nodes.!="sausage"]

In [ ]:
nodes=nodes[nodes.!="sausage"]

In [ ]:
# Gives each unique node an array of berth movements containing the node
#Nodes=Array(Array,length(nodes))
#for i=1:length(nodes)
#    Nodes[i]=Array(String,400)
#end
#s=1
#for i=1:length(nodes)
#    for j=1:length(dataclean)
#        if contains(dataclean[j][23:24]*dataclean[j][27:30],nodes[i])||contains(dataclean[j][25:26]*dataclean[j][31:34],nodes[i])
#            Nodes[i][s]=dataclean[j]
#            s=s+1
#        end
#    end
#    Nodes[i]=Nodes[i][1:s-1]
#    s=1
#end

In [ ]:
# A code that can create a list of nodes of interest based on
# how many unique connections the node has


In [ ]:
# Remove all of the interconnection movements that are created as a 
# result of the border nodes
for l=1:Int64(length(Bordernodes)/2)
    for m=1:length(Interconnections)
        if contains(Interconnections[m],Bordernodes[l,2])
            Interconnections[m]="sausage"
        end
    end
end
Interconnections

In [ ]:
# Removes the interconnection movements that are only observed once
d=1
Interconnect=Array(String,length(Interconnections))
for i=1:length(Interconnect)
    Interconnect[i]="sausage"
end
for i=1:length(Interconnections)
    if Interweights[i]!=1
        Interconnect[d]=Interconnections[i]
        d=d+1
    end
end
Interconnect=Interconnect[Interconnect.!="sausage"]

In [ ]:
# Structures the inter-area movements ina way that it can be read easier
Interconnects=Array(String,length(Interconnect),2)
for i=1:length(Interconnect)
    Interconnects[i,1]=Interconnect[i][1:6]
    Interconnects[i,2]=Interconnect[i][7:12]
end

In [ ]:
# Writes the inter-area movements to a file in the user space
#writedlm("/home/mathsys1/Documents/Trains/Interconnections.csv",Interconnects)

In [13]:
# Creates an array of berth movements that correspond to only one headcode
traintracker=Array(String,length(dataclean))
for i=1:length(dataclean)
    traintracker[i]="sausage"
end
k=1
for l=1:length(trains)
    if trains[l]=="1G29"
        for m=1:length(Trains[l])
            traintracker[k]=Trains[l][m]
            k=k+1
        end
    end
end
traintracker=traintracker[1:k-1]
traintracker

102-element Array{String,1}:
 "1497265223312\$<CA_MSG>ESCA138513871G29115958</CA_MSG>\r\n"
 "1497265223578\$<CA_MSG>ZECA138513871G29115959</CA_MSG>\r\n"
 "1497265236922\$<CA_MSG>ESCA138701011G29120015</CA_MSG>\r\n"
 "1497265237047\$<CA_MSG>ZECA138701011G29120015</CA_MSG>\r\n"
 "1497265242672\$<CA_MSG>D1CA168517111G29120021</CA_MSG>\r\n"
 "1497265266985\$<CA_MSG>ESCA010101031G29120052</CA_MSG>\r\n"
 "1497265267235\$<CA_MSG>ZECA010101031G29120052</CA_MSG>\r\n"
 "1497265288126\$<CA_MSG>ESCA010301051G29120121</CA_MSG>\r\n"
 "1497265288361\$<CA_MSG>ZECA010301051G29120121</CA_MSG>\r\n"
 "1497265319080\$<CA_MSG>ESCA0105R1081G29120158</CA_MSG>\r\n"
 "1497265319315\$<CA_MSG>ZECA0105R1081G29120158</CA_MSG>\r\n"
 "1497265415817\$<CA_MSG>D1CA171117331G29120334</CA_MSG>\r\n"
 "1497265471131\$<CA_MSG>D1CA173317431G29120429</CA_MSG>\r\n"
 ⋮                                                           
 "1497267401356\$<CA_MSG>A3CAN010N0111G29123640</CA_MSG>\r\n"
 "1497267482484\$<CA_MSG>A3CAN011N0121G29

In [14]:
# Display the previous array in a easier to understand format
berthmove=Array(String,length(traintracker),5)
println("       Area1 Area2 From    To     Time")
for i=1:length(traintracker)
    berthmove[i,1]=traintracker[i][23:24]
    berthmove[i,2]=traintracker[i][25:26]
    berthmove[i,3]=traintracker[i][27:30]
    berthmove[i,4]=traintracker[i][31:34]
    berthmove[i,5]=traintracker[i][39:44]
    println(berthmove[i,:])
end

       Area1 Area2 From    To     Time
String["ES","CA","1385","1387","115958"]
String["ZE","CA","1385","1387","115959"]
String["ES","CA","1387","0101","120015"]
String["ZE","CA","1387","0101","120015"]
String["D1","CA","1685","1711","120021"]
String["ES","CA","0101","0103","120052"]
String["ZE","CA","0101","0103","120052"]
String["ES","CA","0103","0105","120121"]
String["ZE","CA","0103","0105","120121"]
String["ES","CA","0105","R108","120158"]
String["ZE","CA","0105","R108","120158"]
String["D1","CA","1711","1733","120334"]
String["D1","CA","1733","1743","120429"]
String["D1","CA","1743","1757","120453"]
String["D1","CA","1757","1767","120527"]
String["D1","CA","1767","1775","120554"]
String["ES","CA","R108","0108","120615"]
String["ZE","CA","R108","0108","120616"]
String["D1","CA","1775","1785","120631"]
String["D1","CA","1785","0793","120724"]
String["D1","CA","0793","0805","120823"]
String["D1","CA","0805","0813","120910"]
String["ES","CA","0108","0106","120925"]
String["ZE","CA","

In [ ]:
Trainpath=Array(String,length(traintracker),2)
for i=1:length(traintracker)
    Trainpath[i,1]=berthmove[i,1]*berthmove[i,3]
    Trainpath[i,2]=berthmove[i,2]*berthmove[i,4]
end
writedlm("/home/mathsys1/Documents/Trains/1Train.csv",Trainpath)

In [ ]:
# Short code that returns a alphabetically sorted list of areas in the
# dataset
Uniqueareas=Array(String,length(dataclean))
for b=1:length(dataclean)
    Uniqueareas[b]="sausage"
end
j=1
for i=1:length(dataclean)
    a=dataclean[i][23:24]
    for k=1:j
        if contains(Uniqueareas[k],a)==true
            s=2
            break
        end
    end
    if s==1
        Uniqueareas[j]=a
        j=j+1
    end
    s=1
end
Uniqueareas=Uniqueareas[1:j-1]
Uniqueareas=sort(Uniqueareas)

In [ ]:
# A code that from the list created earlier finds the first berth
# in an area and creates an array of these berths
LatLong=Array(String,length(Uniqueareas))
k=1
for i=1:length(Uniqueareas)
    for j=1:length(dataclean)
        if dataclean[j][23:24]==Uniqueareas[i]
            LatLong[k]=dataclean[j][23:24]*dataclean[j][27:30]
            k=k+1
            break
        end
    end
end
LatLong

In [ ]:
writedlm("/home/mathsys1/Documents/Trains/LatLong.csv",LatLong)